const shayariList = [
    "Teri yaadon ka sahara hai ab tak, warna main kab ka bikhar gaya hota.",
    "Tumhara khayal aate hi aankhon se neend chali jaati hai.",
    "Jitna chaha utna hi door mila tu mujhe.",
    "Khamoshiyon ka matlab hamesha beparwah nahi hota.",
    "Rishte toot jaate hain awaazon se nahi, lekin unki kami se zaroor.",
    "Humne toh khud ko mita diya us mohabbat mein, jis mein tera naam bhi nahi tha.",
    "Ek waqt tha jab tu zarurat thi, ab yaadon mein bhi nahi aata tu.",
    "Aansuon ne kya khoob nibhaya rishta, har waqt beh kar yaad dilaya tu kaisa tha.",
    "Tanhaayi mein bhi tujhe hi sochte hain, shayad isiliye tanha hain.",
    "Woh khushi thi kisi aur ki, aur dard humare hissa aaya.",
    "Dil todne wale ko toh sirf ek lamha lagta hai, lekin uss toote dil ko sambhalne mein umar beet jaati hai.",
    "Chup rehna bhi ek kala hai, aur hum uss mein hunar mand ho gaye.",
    "Zakhmon pe marham toh sab lagate hain, lekin koi dard nahi chheen sakta.",
    "Main muskura ke jeeta raha sabke saamne, andhar se har din ro diya.",
    "Tere bina sab kuch adhoora lagta hai, jaise kahani mein antim panna hi na ho.",
    "Un lamhon ko kaise bhoolun jahan sirf teri baatein hoti thi.",
    "Tere jaane ke baad zindagi sirf waqt kaatna reh gaya hai.",
    "Aakhri baar uski aankhon mein dekha tha pyaar, uske baad toh bas dooriyaan hi mili.",
    "Waqt ne badla sab kuch, sirf teri yaadon ka asar nahi gaya.",
    "Tu milta toh shayad hum bhi muskurana seekh lete.",
    "Woh muskuraya tha aakhri baar, aur hum samajh nahi paaye alvida tha.",
    "Mohabbat thi isiliye jaane diya, zidd hoti toh baahon mein hota.",
    "Woh keh kar gaya ke main wapas aaoonga, aur waqt bharosa ban gaya.",
    "Kuch rishte sirf yaadon mein hi ache lagte hain.",
    "Humne pucha dard ki had kya hai, usne kaha abhi tak bhool nahi paaye ho usse?",
    "Tere bina jeena toh seekh liya hai, lekin khushi ab bhi tujhmein chhupi hai.",
    "Aansu poochhne wala koi nahi tha, isiliye khud se rishta bana liya.",
    "Har din khud se ek nayi ladai hoti hai, tere bina zindagi ki parchhai hoti hai.",
    "Tumhara khona aise laga jaise zameen se aasman toot gaya ho.",
    "Tumhari yaadon ka ek silsila hai, jo kabhi khatam nahi hota.",
    "Main haar gaya khud se, tumhe jeetne ke chakkar mein.",
    "Ek pal mein bikhar gaya tha main, jab tumne 'bas ab nahi' kaha tha.",
    "Wo roz muskurata tha, aur main roz ro padta tha chupke se.",
    "Rishton mein mohabbat ho ya na ho, wafadari zaroori hoti hai.",
    "Tum chhod gaye ho, lekin main aaj bhi wahi hoon — tere intezaar mein.",
    "Tere bina sab kuch hai, bas dil ke kone mein khaali sa lagta hai.",
    "Tujhe paane ki khwahish thi, par tu toh sirf ek dua ban ke reh gaya.",
    "Waqt ke saath sab kuch badal gaya, bas yaadein wahi ki wahi rahi.",
    "Chaha tha tumhe har haal mein, par tumne toh haalat dekh ke chhod diya.",
    "Maut se darta nahi main, lekin tere bina jeena bhi koi zindagi nahi.",
    "Teri khushi ke liye khud ko bhool gaye, aur tu tha ke humein hi bhool gaya.",
    "Woh waqt hi kuch aur tha jab hum saath the, ab toh bas yaadon ka silsila hai.",
    "Kya faayda us rishtay ka, jisme mohabbat sirf ek taraf se ho.",
    "Ek tere jaane se sab kuch khatam ho gaya, warna zindagi achhi chal rahi thi.",
    "Kabhi kabhi lagta hai tu tha hi nahi, bas mera ek khwab tha.",
    "Tujhse judne ka jazba tha, lekin tu jud ke bhi alag tha.",
    "Aansu toh bahar nikal jaate hain, dard toh dil ke andar hi rehta hai.",
    "Mujhe har roz uska intezaar hota hai, jo kab ka ja chuka hai.",
    "Woh bewafa nahi thi, bas wafaa ki kadar nahi thi usme.",
    "Dil mein basa kar usne hi tod diya, aur hum bas dekhte reh gaye.",
    "Har baar tujhse haar ke bhi tujhi ko chaaha maine.",
    "Kuch baatein kehne se behtar hai unhe mehsoos karna, par tumne toh mehsoos bhi nahi kiya.",
    "Mohabbat uss se thi, jo hamesha ke liye anjaan ban gaya.",
    "Kash kisi din tu laut aaye, bas ek baar gale lag jaaye.",
    "Woh pal jinmein tu tha, aaj bhi meri taqdeer ke sabse khoobsurat hisse hain.",
    "Kahi baar zindagi mein chot lafzon se lagti hai, haathon se nahi.",
    "Jab tak tha tab tak tha, ab toh sirf uski kami reh gayi hai.",
    "Zindagi se koi gila nahi hai, bas tu milta toh baat kuch aur hoti.",
    "Tere jaane ke baad yeh khayal hi nahi raha ke kisi se dil lagaya jaye.",
    "Tu chala gaya lekin tera asar aaj bhi mere chehre se jhalakta hai.",
    "Har baar mujhe hi kyun khona padta hai, kya meri feelings sach nahi hoti?",
  "Kya tumhe kabhi meri yaad nahi aayi, ya main sirf ek waqt ka fasana tha?",
  "Tum saath ho toh sab kuch sahi lagta hai, tum bin toh khud se bhi begana hoon.",
  "Mohabbat thi isiliye chhod diya, agar zidd hoti toh tumhara saath kab ka chheen leta.",
  "Jab bhi teri yaad aayi, aansuon ko samjhaana pada ke sab theek hai.",
  "Ek pal mein sab kuch badal gaya, jaise tu kabhi tha hi nahi.",
  "Jo log dil se jaate hain, unka asar chehre pe nazar aata hai.",
  "Mera dil sirf ek baar toda gaya tha, par har roz dard hota raha.",
  "Tu juda ho gaya par khayalon mein roz milta hai.",
  "Jab dard likhne lage, samajh jao ke pyaar sach tha.",
  "Tum meri zindagi ka wo hisa ho jo chhod kar bhi mita nahi.",
  "Kya tumne kabhi mehsoos kiya, us khamoshi ka dard jo maine jhela?",
  "Raat bhar aansuon ki barsaat thi, aur wajah sirf tum the.",
  "Na koi gila na koi shikwa hai, bas tu yaad bahut aata hai.",
  "Tere jaane ke baad zindagi ka har pal ek saza lagta hai.",
  "Kuch yaadein itni gehri hoti hain ke waqt bhi unhe nahi mita sakta.",
  "Tere saath bitaye pal hi meri pehchan the, tu gaya toh main bhi kho gaya.",
  "Kya fayda uss mohabbat ka jo teri muskurahat se bhi mehroom rahi?",
  "Woh ek pal jab tune roka nahi, zindagi bhar ka dard de gaya.",
  "Ek waqt tha jab tu sab kuch tha, ab sirf ek adhoori kahani hai.",
  "Tujhse juda hoke bhi tujhmein hi zinda hoon.",
  "Tere jaane ke baad har muskurahat jhooth lagti hai.",
  "Main us mod pe hoon jahan na tum ho na koi aur.",
  "Har dard ki wajah tum nahi ho, lekin tumhare baad dard zarur shuru hua.",
  "Jo log toot kar chahte hain, woh hi sabse zyada toot jaate hain.",
  "Chhoti si mulaqat ne zindagi badal di, aur ek alvida ne sab kuch khatam.",
  "Tere jaise bewafaa se pyaar karna bhi apraadh lagta hai.",
  "Waqt ne badla sab kuch, par teri yaadon ka rang ab bhi gehra hai.",
  "Tumse bichhadne ke baad samjha maine, tanhaayi kya hoti hai.",
  "Zakhm toh sab ko milte hain, par dard ka silsila sirf mohabbat mein hota hai.",
   "Aankhon mein aansu the, par hum muskura rahe the sabke liye.",
  "Tere bina zindagi adhuri lagti hai, jaise geet ke bina sangeet.",
  "Woh muskuraya zarur tha, par aankhon mein judaai thi.",
  "Kisi aur ke naseeb mein likha gaya tha, warna mohabbat toh humne dil se ki thi.",
  "Na tu mera tha, na tu kisi aur ka ho saka.",
  "Main us mod pe aaya hoon, jahan se wapas jaana mumkin nahi.",
  "Tere bina jeena toh seekh liya, par khush rehna abhi bhi nahi aata.",
  "Waqt guzarta gaya, lekin tera intezaar nahi.",
  "Mujhe bewajah chor diya tune, aur wajah tak nahi batayi.",
  "Kya tum kabhi laut ke aane wale ho, ya main bas intezaar hi karta rahunga?",
  "Tere jaane ke baad khud se bhi dar lagne laga hai.",
  "Tu bewajah chala gaya, aur main har wajah dhoondta raha.",
  "Tere hone ka ehsaas ab bhi zinda hai, tu nahi hai bas.",
  "Jo dard diya tune, uska ilaaj kahin nahi milta.",
  "Mohabbat ke badle sirf khamoshi mili.",
  "Aaj bhi tere naam se dil tez dhadakta hai, jaise kal hi mulaqat hui ho.",
  "Tu samjha hi nahi kabhi meri khamoshi ko.",
  "Mujhe tod kar bhi tu chain se so gaya, wah re mohabbat.",
  "Chaha tha tujhe jeene ki tarah, aur tu mila khwab ki tarah.",
  "Tere baad har rishta bas ek formal sa lagta hai.",
  "Woh waqt wapas laa de koi, jahan sirf hum the.",
  "Kya fayda aise pyaar ka, jisme bharosa hi na ho.",
  "Tere baad humne khud ko hi khona shuru kar diya.",
  "Woh log aksar bewafa nikalte hain, jinke liye hum duniya bhool jaate hain.",
  "Mujhse juda hokar bhi tu har jagah dikhta hai.",
  "Jab tak tu saath tha, har gham asaan lagta tha.",
  "Na gila hai na shikwa, bas tu yaad bahut aata hai.",
  "Mohabbat mein haar gaya, lekin nafrat mein kabhi aaya hi nahi.",
  "Tere saath bitaye lamhe hi mere jeene ka sahara hain.",
  "Woh rishte bhi kya rishte hain, jisme dil se dil juda na ho.",
  "Aansu bol nahi sakte, par sab kuch keh jaate hain.",
  "Tu toh gaya, lekin tere jaane ke baad main kabhi waapas nahi aaya.",
  "Tujhse juda hokar pata chala, mohabbat sirf dard ka naam hai.",
  "Waqt ka dard nahi hota, yaadon ka bojh hota hai.",
  "Mere jazbaat sirf mere the, tumhare liye toh bas waqt tha.",
  "Dil se chaha tha tumhe, par tumne samjha hi nahi.",
  "Zindagi wahi thi, bas usmein tu nahi tha.",
  "Jin raaton mein tu yaad aata hai, woh subah kabhi achhi nahi hoti.",
  "Na ro sakte hain, na kisi se keh sakte hain — bas tere baare mein soch sakte hain.",
  "Kabhi kabhi khud se bhi puchhta hoon — kya usne kabhi chaha bhi tha?"
  ];
  
  function getRandomShayari() {
    const randomIndex = Math.floor(Math.random() * shayariList.length);
    return shayariList[randomIndex];
  }
  
  function showNewShayari() {
    const displayDiv = document.querySelector(".apt");
    if (displayDiv) {
      displayDiv.textContent = getRandomShayari();
    }
  }
  
  // Link the button after DOM is ready
  document.addEventListener("DOMContentLoaded", () => {
    const btn = document.querySelector(".clck");
    if (btn) {
      btn.addEventListener("click", showNewShayari);
    }
  });
  