const shayariList = [
    "Tere bina bhi zindagi khoobsurat lagti hai, kyunki umeed ab bhi zinda hai.",
    "Har andhera roshni ke liye jagah banata hai.",
    "Mohabbat wahi jo har dard mein muskurahat de.",
    "Tu mila toh laga khud se mulaqat ho gayi.",
    "Waqt thoda sa sahi, magar sab kuch badal sakta hai.",
    "Tumhari muskurahat mere din ka noor ban jaati hai.",
    "Sache jazbaat waqt ke mohtaaj nahi hote.",
    "Zindagi har pal naya raag chhedti hai, bas sunne wala chaahiye.",
    "Tum ho toh har mausam suhana lagta hai.",
    "Dil se nikalti dua kabhi khali nahi jaati.",
    "Pyar wahi hai jo har dafa nayi roshni ban kar aaye.",
    "Jitni baar toota hoon, utni baar nayi umeed le aaya hoon.",
    "Tere sath ki yaadein har din me ek rang bhar jaati hain.",
    "Musibat mein jo muskura de, wahi asli shayar hota hai.",
    "Zindagi jeene ka maza tab aata hai jab koi apna saath ho.",
    "Aankhon mein sapne ho, aur dil mein himmat ho toh raasta mil hi jaata hai.",
    "Pyaar sirf izhaar ka naam nahi, samajhne ka silsila hai.",
    "Kisi ke liye zaroori banna, sabse khoobsurat ehsaas hota hai.",
    "Khushiyan baantne se badhti hain, dard baantne se kam hote hain.",
    "Kabhi kabhi ek muskurahat hi kaafi hoti hai din banane ke liye.",
    "Tumhari yaadon ka rang ab bhi mere khwabon mein hai.",
    "Pyaar mein haara nahi jata, bas thoda ruk kar jeeta jata hai.",
    "Jo dil se nikalti hai, woh baat dil tak zaroor jaati hai.",
    "Tera saath ho toh har raasta asaan lagta hai.",
    "Zindagi ne har mod par kuch sikhaya, par tera pyaar sabse khoobsurat sabak tha.",
    "Khush rehne ke liye wajah nahi, bas jazba chahiye.",
    "Woh pal jab tu paas tha, aaj bhi mere liye ek poori zindagi hai.",
    "Jahan pyaar hota hai, wahan har cheez khoobsurat lagti hai.",
    "Dil ke rishtay lafzon ke mohtaaj nahi hote.",
    "Chup rehkar bhi tu meri duniya keh jaata hai.",
    "Kamyabi se pehle sab kuch mushkil lagta hai, par ek muskurahat sab kuch badal deti hai.",
    "Tum ho toh har ghadi mein ek nayi umeed hoti hai.",
    "Tere bina bhi jee rahe hain, par tere sath rehna jeena kehlaata hai.",
    "Jab dil saaf ho, toh chehra roshan rehta hai.",
    "Pyaar sirf lamhon ka saath nahi, ek zindagi ka safar hota hai.",
    "Tu aaye ya na aaye, mera dil tere naam ka hai.",
    "Har kal ke liye ek nayi subah hoti hai.",
    "Tere sath ki khamoshi bhi geet lagti hai.",
    "Zindagi mein har kisi ko khush rakhna mumkin nahi, lekin dil se koshish zaroor karo.",
    "Tumhara hona mere liye ek dua ka poora hona hai.",
    "Mohabbat mehsoos hoti hai, bayaan nahi ki jaati.",
    "Jitna bhi gham ho, tere ek text se sab kuch theek lagta hai.",
    "Dil pe likhi teri muskurahat, meri favourite poetry hai.",
    "Kuch log milkar zindagi mein rang bhar dete hain.",
    "Sacha pyaar waqt ka mohtaaj nahi hota.",
    "Jahan pyaar hota hai, wahan har din Eid hota hai.",
    "Jab tu hamesha ke liye chala gaya, tab samjha ke khushi ka matlab kya hota hai — aur uski kami ka bhi.",
    "Apna banana sabko aata hai, magar nibhaana sabka kaam nahi hota.",
    "Tu aaye toh zindagi mein rang ho jaaye, warna hum toh waise bhi rangrez hain.",
    "Jo log dil se hote hain, woh yaad banke kabhi nahi jaate.",
    "Har muskurahat ke peeche ek kahani hoti hai, aur meri kahani tu hai.",
  "Zindagi khud ek tofa hai, bas use samajhne ki der hai.",
  "Jitni baar gira hoon, utni baar tere naam pe khud ko sambhala hai.",
  "Tera hona meri zindagi ka sabse haseen hisa hai.",
  "Jo sapne tujhse jude hoon, woh kabhi adhure nahi lagte.",
  "Zindagi ki har subah naye jazbaat laati hai.",
  "Mohabbat mein haar bhi jeet se behtar lagti hai.",
  "Teri hansi mere liye ek nayi subah ka ehsaas hai.",
  "Chhoti chhoti khushiyon mein bhi teri yaad bas jaati hai.",
  "Dil tootta hai, par umeed kabhi nahi.",
  "Tere saath bitaye pal yaadon ka jahan ban gaye hain.",
  "Khushi ka asli matlab sirf tere aas paas hona hai.",
  "Chand ke paas bhi agar kuch kami hai, toh woh tera saath hai.",
  "Roshni tabhi tak hai jab tak tu meri zindagi mein hai.",
  "Dil ki zubaan kabhi jhoot nahi bolti.",
  "Tum ho, isliye sab kuch poora lagta hai.",
  "Jo tu samjhta hai, woh baaki koi nahi samajh sakta.",
  "Tumhare hone se zindagi ek mehfil lagti hai.",
  "Khud pe vishwas rakhna, zindagi badalne ka pehla kadam hota hai.",
  "Ek pal mein sab kuch badal sakta hai, agar niyat saaf ho.",
  "Zindagi mein kuch rishte lafzon ke bagair bhi gehre ho jaate hain.",
  "Tera naam le kar har subah nayi umeed jagti hai.",
  "Waqt sab kuch le jata hai, par yaadein kabhi nahi jaati.",
  "Pyaar wo nahi jo dikha diya jaye, pyaar wo hai jo har waqt mehsoos ho.",
  "Muskurana meri aadat ban gayi hai, kyunki tu meri zindagi mein hai.",
  "Tu door hai phir bhi mere dil ke paas hai.",
  "Har kisi ko apni zindagi mein ek aise insaan ki zarurat hoti hai jo sirf samjhe.",
  "Tere sath ke bina bhi jee rahe hain, par uss jeene mein maza nahi hai.",
  "Umeed ka ek diya andheron ko bhi roshan kar sakta hai.",
  "Tu milta toh zindagi aur bhi khoobsurat hoti.",
  "Kya baat hai tere chehre ki, har baar ek nayi mohabbat hoti hai.",
  "Dil ki awaaz bhi tu hi hai, aur uska sukoon bhi.",
  "Zindagi se gile nahi, bas kuch sapne adhure reh gaye.",
  "Tumhare sath chalna hi mere liye kaafi hai.",
  "Har pal tera intezaar karna, ab aadat si ban gayi hai.",
  "Kuch log yaadon mein bas jaate hain, aur kabhi nahi nikalte.",
  "Tum mil jao, toh zindagi se aur kya chahiye?",
  "Pyaar ek ehsaas hai, jo lafzon ka mohtaaj nahi hota.",
  "Tere hone se har din ek nayi kahani ban jaati hai.",
  "Tu paas ho ya door, har lamha tu hi tu hai.",
  "Sache jazbaat kabhi purane nahi hote.",
  "Tera naam lete hi dil ka har kona roshan ho jaata hai.",
  "Mohabbat sirf milne ka naam nahi, mohabbat toh uss yaad ka naam hai jo kabhi jaati nahi.",
  "Tu meri zindagi ka sabse khubsurat kismat hai.",
  "Zindagi ke har mod pe teri yaad ka saath hai.",
  "Jo teri hansi dekh le, usse aur kuch dekhna nahi hota.",
  "Tere bina bhi jeet liya hai khud ko, par tere sath hona behtareen hota.",
  "Tujhse milne ke baad khud se pyaar karna aaya.",
  "Tumhare hone se meri duniya ek geet ban gayi hai.",
  "Jitni baar socha tujhe bhool jaun, utni baar tere pyaar mein doob gaya.",
  "Tere naam se meri subah hoti hai, aur teri yaadon se shaam.",
  "Zindagi tab khoobsurat lagti hai jab dil mein shukriya hota hai.",
  "Har kisi ka waqt aata hai, bas ruk kar intezaar karna padta hai.",
  "Tere saath hone ka matlab hai khud se mohabbat karna.",
  "Tum ho toh har safar suhana hai.",
  "Tere muskurane se mere dard chup ho jaate hain.",
  "Umeedon ka diya andheron se kabhi nahi darta.",
  "Tera pyaar meri jeet ka saboot hai.",
  "Khush rehna bhi ek ibadat hai.",
  "Tu samne ho ya nahi, tera hona mehsoos hota hai.",
  "Dil se nikli dua hamesha manzil tak jaati hai.",
  "Zindagi ek safar hai, tu saathi ho toh har mod pyara lagta hai.",
  "Tera saath mil jaaye, toh aur kuch na chaahiye.",
  "Aankhon mein sapne ho aur dil mein tu, bas yehi kaafi hai.",
  "Tu door ho, par dil ke itne kareeb ke har saans tujhmein mehsoos hoti hai.",
  "Pyaar wahi jo waqt ke saath aur gehra ho jaaye.",
  "Kabhi khud se bhi pyaar karna seekho, tabhi duniya se pyaar kar paoge.",
  "Mohabbat mein shartein nahi hoti, sirf jazbaat hote hain.",
  "Tere khayalon mein hi apni duniya basayi hai.",
  "Zindagi ne jitna rulaya, tu milke utna hasaya."
  ];
  
  function getRandomShayari() {
    const randomIndex = Math.floor(Math.random() * shayariList.length);
    return shayariList[randomIndex];
  }
  
  function showNewShayari() {
    const displayDiv = document.querySelector(".apt");
    if (displayDiv) {
      displayDiv.textContent = getRandomShayari();
    }
  }
  
  // Link the button after DOM is ready
  document.addEventListener("DOMContentLoaded", () => {
    const btn = document.querySelector(".clck");
    if (btn) {
      btn.addEventListener("click", showNewShayari);
    }
  });
  