const shayariList = [
    "Tum aaye toh zindagi mein rangon ka tyohar aa gaya.",
  "Mohabbat bhi ek imtihaan hai, jo sabko paas nahi karta.",
  "Woh khamoshi bhi keh gayi sab kuch, jo alfaaz nahi keh paaye.",
  "Chai bhi teri yaadon jaise hai, kadvi bhi, meethi bhi.",
  "Main aur meri tanhayi, aksar yeh baatein karte hain...",
  "Jab tu saath tha, zindagi bhi shaayar thi.",
  "Dil se nikli baat dil tak jaati hai, bas rasta kabhi kabhi bhatak jaata hai.",
  "Woh whatsapp pe toh online tha, par meri zindagi se offline.",
  "Aankhon mein sapne lekar chala tha, tere khayalon ne rasta badal diya.",
  "Zindagi ka asli maza toh tab aata hai jab wifi slow ho aur hum shaayar ban jaayein.",
  "Tere bina subah bhi shaam lagti hai.",
  "Ek baar mil jaa, fir waada hai tujhe jaane nahi dunga... jab tak recharge hai.",
  "Tere bina toh dil laptop jaise ho gaya, fan chalta hai par thandak nahi milti.",
  "Mohabbat mein sirf dil nahi, poora data pack chala jaata hai.",
  "Uske chehre pe no-makeup look tha, aur dil pe full damage.",
  "Zindagi ki kitaab mein tu sabse haseen chapter tha.",
  "Woh aakhri seen tha mere pyaar ka, jab usne mujhe 'bhai' kaha.",
  "Bohot dino baad usne contact kiya, bas recharge karwana tha.",
  "Mohabbat phone ki tarah hoti hai, network ho toh baat hoti hai.",
  "Meri shayari ka hero bhi tu hai, villain bhi tu hi.",
  "Usne kaha: 'tu kuch bhi likh le, main tere liye nahi hoon.'",
  "Zindagi toh chalti jaa rahi hai, par tu wahi ruk gaya hai dil mein.",
  "Log kehte hain waqt sab kuch sahi kar deta hai, par tu abhi bhi yaadon mein hai.",
  "Pyaar toh sab karte hain, mazaak bhi sab ban jaate hain.",
  "Kal tak jo apna tha, aaj sirf status ka part hai.",
  "Tujhse alag hona bhi ek fan-following jaisa tha, sab notice kar rahe the.",
  "Tera naam jab bhi likhta hoon, dil thoda aur dukhta hai.",
  "Jo chala gaya, woh taqdeer tha. Jo reh gaya, woh tasveer hai.",
  "Tere saath waqt guzarna koi waqt zaya nahi tha.",
  "Main tere khayalon mein bhi royalty feel karta hoon.",
  "Woh toh chala gaya, par uski yaadein still active hain.",
  "Tere baad kisi se dil laga hi nahi, wifi toh milta hai, par password nahi.",
  "Zindagi aur tu, dono samajh ke bahar ho.",
  "Shayari likhne ka shauk nahi tha, par tere jaane ke baad aadat ho gayi.",
  "Woh dost thi, par dil dosti se zyada sochta tha.",
  "Uske jaane ke baad, playlist bhi sad ho gayi.",
  "Tere bina toh traffic bhi romantic lagta hai.",
  "Mausam toh badalte hain, tu kyun nahi badla?",
  "Tere aane se zindagi theek thi, ab toh Instagram stories hi sahara hain.",
  "Pyar mein har kisi ka status complicated hota hai.",
  "Kabhi jo baat nahi ki, aaj woh yaadon mein roz baat karti hai.",
  "Tera naam lena bhi ek ibadat jaisa lagta hai.",
  "Mohabbat ek game hai, aur main har level pe haar gaya.",
  "Usne kaha, 'chal bhool ja,' aur main writer ban gaya.",
  "Ek baar toh usne pyaar se dekha hota, main shaayar ban jaata.",
  "Tera chehra yaad hai, par mood delete ho chuka hai.",
  "Zindagi ne sikhaya, ke rishton mein logic nahi, sirf timing chahiye.",
  "Waqt ke saath sab kuch badal gaya, par tera number ab bhi yaad hai.",
  "Main uska the, par uske status mein koi aur tha.",
  "Tere jaane ke baad bhi, maine apne status sad hi rakhe.",
  "Har roz ek nayi yaad aati hai, aur ek purani chubh jaati hai.",
  "Tere bina zindagi whatsapp ke bina phone jaisi hai.",
  "Woh milti toh thi, par aankhon se nazar nahi aati thi.",
  "Shayari likhne ka reason tu tha, ab tu nahi toh rhyme bhi nahi.",
  "Tere jaane ke baad diary likhna start kiya, ab 3 volumes ho chuki hain.",
  "Pyar dikhana sabko aata hai, nibhana kisi kisi ko.",
  "Main har raat tujhe yaad karta hoon, aur tu har subah bhool jaati hai.",
  "Tu toh wo chapter tha jo syllabus mein tha hi nahi, par dil fail karwa gaya.",
  "Teri aankhon mein kuch baat thi, tabhi toh main dooba tha.",
  "Ab toh tere yaadon ka bhi backup nahi banata, direct delete karta hoon.",
  "Woh waqt accha tha jab tu anpadh thi, status nahi update karti thi.",
  "Tere aage sab kuch bekaar lagta hai, Facebook bhi.",
  "Tere bina toh coffee bhi kadwi lagti hai, par lena padti hai.",
  "Har bar teri yaad aati hai, aur har bar main 'seen' reh jaata hoon.",
  "Pehle tujhmein dil lagta tha, ab toh bas dimag kharab hota hai.",
  "Woh kehti thi, 'tum unique ho' — tab samjha unique = akela.",
  "Main tere bina incomplete hoon — jaise pdf without password.",
  "Uske liye toh main ek file tha — download, use, delete.",
  "Teri yaadein password ki tarah hain, har jagah chhupi hain par zaroori.",
  "Kuch baatein sirf diary samajhti hai, log nahi.",
  "Pyaar ek risk hai, aur main insurance ke bina le baitha.",
  "Ab toh status bhi nahi dekhta, direct logout ho gaya hoon.",
  "Tere jaane ke baad shayari likhne laga, ab tu hi likh ke dikha.",
  "Tere bina har baat adhuri lagti hai, jaise bina chutney ke samosa.",
  "Aankhon mein aansu nahi, par dil mein tsunami hai.",
  "Pyaar toh kiya tha, par return policy nahi thi.",
  "Woh likhne wali ladki thi, main padhne wala... story adhuri reh gayi.",
  "Tera naam sunte hi jo smile aati thi, ab woh silence mein badal chuki hai.",
  "Ab toh tu sirf dp mein acchi lagti hai.",
  "Mohabbat bhi app jaisi hai, sab use karte hain, par samajhte nahi.",
  "Waqt guzar gaya, par woh 'last seen' yaad hai.",
  "Tumhara naam jab bhi likha, pen ne rukne se inkaar kiya.",
  "Tujhse bichadne ke baad, dil ne khud se bhi milna chhod diya.",
  "Main tujhmein nahi tha, aur tu har jagah thi.",
  "Aankhon ne toh dekha nahi, par dil tujhmein base jaata tha.",
  "Woh toh sirf ek pal thi, par yaadein hamesha ke liye de gayi.",
  "Tera naam lena har roz ka nasha ho gaya hai.",
  "Har baar tu yaad aayi, aur main likhta gaya.",
  "Tere baad kisi aur ko dekhne ka mann hi nahi hota.",
  "Usne kaha tha 'hamesha saath rahenge', ab toh reply bhi nahi aata.",
  "Mohabbat kehte hain uss jazbaat ko, jo tujh tak nahi pohoch saka.",
  "Kabhi uski muskurahat mein apna aashiyana dhoondha tha.",
  "Teri har baat, meri kalam ki aakhri line hoti thi.",
  "Uska chehra meri diary ka cover page ban gaya hai.",
  "Kya fayda uss pyaar ka, jo screenshot tak simat gaya?",
  "Zindagi ne sab kuch diya, bas tu nahi mila.",
  "Tere baare mein likhna aisa hai jaise khud pe kitaab likhna.",
    "Tumse milke laga zindagi ko maqsad mil gaya.",
    "Tu juda hua toh samjha pyaar kya hota hai.",
    "Teri yaadon ka sahara hai, warna main kab ka toot gaya hota.",
    "Uske ek text ka intezaar bhi ek kahani ban gaya hai.",
    "Woh pyaar hi kya jisme majnu wali diwaangi na ho.",
    "Ab toh kisi ke aane se bhi khushi nahi hoti, kyunki tu nahi aata.",
    "Uske saath bitaye pal ab photo album ban chuke hain.",
    "Tera zikr aaye toh aankhon ka bhar aana lazmi hai.",
    "Har baar tujhe bhoolne ki koshish mein thoda aur yaad kar leta hoon.",
    "Pehle tu thi toh har cheez mein rang tha, ab sab kuch feeka lagta hai.",
    "Tere jane ke baad har geet adhura sa lagta hai.",
    "Tum mil jaate toh kahani kuch aur hoti.",
    "Tere bina har dard ka ek hi ilaaj hai — waqt.",
    "Mohabbat ek ehsaas hai, jo sabko mehsoos nahi hota.",
    "Tujhse baat na ho toh din nahi guzarta.",
    "Tere jaane ke baad toh khud se bhi baatein nahi hoti.",
    "Pyar toh sach mein andha hota hai, tabhi toh tu nazar nahi aaya.",
    "Tera gussa bhi pyaar lagta tha, ab toh sirf yaad reh gaya hai.",
    "Uski har muskaan mein ek nasha tha, jo aaj bhi chadh jaata hai.",
    "Main tere intezaar mein waqt se bhi lad gaya.",
    "Uski aankhon mein doobhne ka man karta tha.",
    "Teri yaadon ka ek alag hi nasha hai, jo kabhi utarta hi nahi.",
    "Ab toh khud se bhi keh diya hai, ke bhool ja usse.",
    "Har kisi mein tu dikhne laga hai, bas tu nahi dikhta.",
    "Teri hansi ka asar ab bhi dil pe hai.",
    "Woh pal jab tu paas thi, ab tasveer ban chuke hain.",
    "Kya fayda uss mohabbat ka, jisme tu tha hi nahi.",
    "Tujhse milkar laga har dard mit gaya, par tu chali gayi.",
    "Mohabbat mein har koi khud ko bhool jaata hai.",
    "Tere saath chalti zindagi ek khoobsurat safar thi.",
    "Jab tu saath hoti thi, toh har raat Eid si lagti thi.",
    "Tu nahi toh mehfil bhi veeran lagti hai.",
    "Teri yaadon ka ek kona dil mein hamesha zinda rahega.",
    "Woh teri khamoshi bhi kuch keh jaati thi.",
    "Tujhe dekhkar hi toh shayari likhna aaya.",
    "Mohabbat mein haar kar bhi jeet ka ehsaas hota hai.",
    "Teri har ek baat dil ko choo jaati hai.",
    "Woh lamha jab tu roothi thi, ab tak yaad hai.",
    "Tu door hoke bhi kareeb lagti hai.",
    "Pehli baar tujhe dekha, toh samjha mohabbat kya hoti hai.",
    "Tere bina har rang udaas hai.",
    "Tujhmein kuch toh baat thi jo sab kuch bhula diya.",
    "Tere saath har pal ek kahani ban gaya.",
    "Jab tak tu thi, tab tak sab kuch sahi tha.",
    "Usne kaha tha 'main laut aungi', ab tak intezaar hai.",
    "Tere bina zindagi ka maza nahi aata.",
    "Woh pal jab tu hasti thi, sabse khaas the.",
    "Mohabbat kehte hain uss rishtay ko jo bina mile bhi jud jaata hai.",
    "Tera saath mila, toh har gum door ho gaya.",
    "Teri baat ho aur aankhon mein aansu na aaye, aisa ho nahi sakta.",
    "Uski ek muskaan dil ko jeet leti thi.",
    "Pyar ka matlab hi tu thi mere liye.",
    "Tujhse milkar har ek dard pyaara lagta tha.",
    "Tera naam mere har lafz mein chhupa hota hai.",
    "Woh yaad bhi aati hai aur rulati bhi hai.",
    "Tere bina toh waqt guzarna mushkil hai.",
    "Har raat tujhe sochkar hi nind aati hai.",
    "Teri aankhon ka noor ab bhi mere khwab mein aata hai.",
    "Tujhe bhoolne ki har koshish mein tu aur yaad aata hai.",
    "Mohabbat mein bas tera naam kaafi hai.",
    "Tere saath zindagi gulzar thi.",
    "Uski baatein ab bhi kaano mein goonjti hain.",
    "Tera khayal har waqt mere saath chalta hai.",
    "Tujhse bichhad kar sab kuch adhura lagta hai.",
    "Uski har ek muskaan mein duniya chhupi thi.",
    "Tere bina zindagi mein kuch bhi khas nahi.",
    "Woh yaadein ab bhi taaza hain.",
    "Tu chali gayi, par dil wahi ka wahi reh gaya.",
    "Usne sirf alvida kaha tha, aur hum tut gaye.",
    "Tere saath har gham asaan lagta tha.",
    "Tujhe dekhkar hi toh likhne ka hunar aaya.",
    "Woh pal jab hum saath the, ab sirf khwab hai.",
    "Tera naam lena har baar ek nayi kasak deta hai.",
    "Tujhe paa kar bhi khona pada.",
    "Tere saath rehkar har dard meetha lagta tha.",
    "Mohabbat ek junoon hai, jo tujhmein tha.",
    "Tera saath mila, toh duniya jeet li.",
    "Woh yaad jo tujhmein thi, ab mere geet ban gayi.",
    "Tu door sahi, par har dil ki dhadkan mein hai.",
    "Tere bina sab kuch adhura hai.",
    "Pyar ki har raah tujhmein jaake rukti hai.",
    "Tujhse juda hokar bhi tere saath hi jee raha hoon.",
    "Teri muskaan meri jaan thi.",
    "Uske khayal mein hi jeevan ka saar tha.",
    "Teri yaadon ka sahara hai, warna main kab ka gir chuka hota.",
    "Mohabbat teri adhoori sahi, par meri toh poori thi.",
    "Tujhse juda hokar bhi tere saath hi hoon.",
    "Usne kaha tha 'tum mere ho', aur main sach maan gaya.",
    "Teri aankhon mein poori duniya dikhti thi.",
    "Tere bina toh khushi bhi bekar lagti hai.",
    "Har baar tujhe dekh kar nayi duniya ka ehsaas hota tha.",
    "Tujhse baat karna mere din ka sabse khoobsurat hissa hota tha.",
    "Tere naam se hi meri saansein chalti thi.",
    "Teri hansi meri kamzori ban gayi thi.",
    "Tujhe paa kar lagta tha zindagi jeet gaya.",
    "Mohabbat mein sab kuch haara, bas tujhe jeeta.",
    "Tu nahi toh har rasta bekaar lagta hai.",
    "Tere saath guzre lamhe ab yaadon ka sahara hain.",
    "Tujhse pyaar karna meri aadat ban gayi thi.",
    "Tere hone se hi toh khud pe yakeen tha.",
    "Woh pal jab tu muskurayi thi, sabse haseen tha.",
    "Teri ek nazar kaafi thi dil jeetne ke liye.",
    "Tu door hai lekin har pal saath hai.",
    "Tere bina zindagi ka har din bejaan hai.",
    "Mohabbat tujhmein khud ka wajood dhoondhti hai.",
    "Tujhe dekhkar hi toh dil ne dhadakna seekha tha.",
    "Tu milti toh har dua qubool hoti.",
    "Woh teri khamoshi bhi kitni shor machati thi.",
    "Tere jaane ke baad tanhaayi se dosti ho gayi.",
    "Pyaar sirf tujhi se tha, hai aur rahega.",
    "Tere saath bitaye lamhe dil ke kone mein base hain.",
    "Tu nahi toh khud se bhi milna chhod diya hai.",
    "Tujhmein jo baat thi, woh kisi mein nahi.",
    "Har baar tujhe sochkar aankhon se baarish hoti hai.",
    "Tere bina toh khushi bhi muskurana bhool gayi hai.",
    "Tere hone ka ehsaas hi kaafi tha.",
    "Teri ek muskaan se din ban jaata tha.",
    "Woh lamha jab tu paas thi, ab sirf yaad hai.",
    "Tere naam se hi dil dhadakne lagta hai.",
    "Tujhe chhod kar chalna sabse mushkil kaam tha.",
    "Uski yaadein aaj bhi dil ko rulati hain.",
    "Mohabbat mein sab kuch khona padta hai.",
    "Tujhse milne ka junoon har roz tha.",
    "Tu door hokar bhi har jagah nazar aata hai.",
    "Tere saath tha toh khud pe fakhar tha.",
    "Tere jaane se zindagi se rang chala gaya.",
    "Pyaar toh tab hua jab teri aankhon mein aansu dekha.",
    "Woh teri baat jo adhuri reh gayi, ab tak sochta hoon.",
    "Tujhse door rehna ek saza ban gayi hai.",
    "Teri muskurahat ab bhi khwab ban ke aati hai.",
    "Tere bina likhna bekaar lagta hai.",
    "Har ek line tujhi se shuru hoti hai.",
    "Tu nahi, par tera asar hai zindagi mein.",
    "Woh dard jo tu de gaya, ab jeevan saathi ban gaya hai.",
    "Teri yaadon ka bojh ab aadat ban gaya hai.",
    "Tujhse pyaar ek misaal hai, jiska anjaam nahi.",
    "Uske bina har geet adhoora hai.",
    "Teri hansi mere din ka ujala thi.",
    "Mohabbat ke har pehlu mein tu hi tu tha.",
    "Tu nahi, lekin teri kami har waqt hai.",
    "Tere saath ki talash ab bhi hai.",
    "Tere bina har safar tanha hai.",
    "Teri ek baat se zindagi badal jaati thi.",
    "Woh mulaqat ab bhi dil mein basa rakhi hai.",
    "Tujhse juda hokar sab kuch feeka hai.",
    "Teri har baat mein ek kashish thi.",
    "Tere hone se har chehra roshan tha.",
    "Tujhse juda hokar andhera chhane laga.",
    "Teri aankhon ka jadoo ab bhi hai.",
    "Tu nahi toh har mehfil adhoori hai.",
    "Woh yaadein jo tere saath judi hain, kabhi purani nahi hoti.",
    "Tujhse mohabbat har roz nayi lagti thi.",
    "Teri khamoshi bhi dil ko behla jaati thi.",
    "Tujhse door hokar bhi tu paas lagta hai.",
    "Woh baat jo tere dil mein thi, ab samajh mein aati hai.",
    "Teri kami har cheez mein mehsoos hoti hai.",
    "Tu har waqt yaadon mein zinda hai.",
    "Mohabbat mein sirf tu thi, baaki sab bekaar tha.",
    "Teri muskaan meri zindagi thi.",
    "Woh lamha jab tu gale lagi thi, sabse khaas tha.",
    "Tere bina sab kuch bekaar lagta hai.",
    "Tu thi toh har waqt ek tasalli thi.",
    "Tujhe dekhkar hi toh likhne ka jazba aaya.",
    "Woh teri aankhon ka noor ab bhi yaadon mein hai.",
    "Tere saath guzre pal ab geet ban gaye hain.",
    "Teri baaton mein ek sukoon tha.",
    "Tere saath rehkar har waqt ek nasha tha.",
    "Tere jaane ke baad sab kuch khaali hai.",
    "Tujhse milkar har baat khas ho jaati thi.",
    "Tere hone ka ehsaas har waqt tha.",
    "Mohabbat ka matlab hi tu thi.",
    "Tu nahi toh sab kuch adhura lagta hai.",
    "Woh pal jab hum saath the, ab khwab hain.",
    "Teri ek muskaan sab kuch theek kar deti thi.",
    "Tere saath ka har lamha yaadon mein hai.",
    "Tere bina toh likhna bhi adhura lagta hai.",
    "Woh teri baat jo adhuri reh gayi thi, ab tak yaad hai.",
    "Tere saath rehkar hi toh zindagi thi.",
    "Tujhse juda hokar dil suna ho gaya hai.",
    "Tere khayalon mein hi toh likhna aata hai.",
    "Tu thi toh har waqt ek chamak thi.",
    "Tere bina har cheez bejaan hai.",
    "Tere saath ki yaadein ab bhi zinda hain.",
    "Mohabbat ki har baat tujhmein thi.",
    "Tujhse door hokar bhi tu dil ke paas hai.",
    "Woh lamha jab hum mile the, ab bhi yaad hai.",
    "Tere jaane ke baad khud se rishta toot gaya.",
    "Tujhmein hi toh meri duniya basi thi.",
    "Tu door sahi, lekin har pal yaadon mein hai.",
    "Tere naam se hi geet ban jaate hain.",
    "Tere saath ki ek muskaan sab kuch badal deti thi.",
    "Tu thi toh har waqt ek kahaani thi.",
    "Tujhse juda hokar bhi tujhmein jeete hain.",
    "Teri yaadon ka asar ab tak hai.",
    "Tu nahi, lekin tera pyaar har waqt saath hai.",
    "Mohabbat tujhmein thi, ab yaadon mein hai.",
    "Tujhse juda hokar sab kuch kho diya.",
    "Tere saath har lamha ek shayari ban gaya.",
    "Teri baaton mein ek jadoo tha.",
    "Tu door hokar bhi har waqt paas thi.",
    "Tere bina toh kuch bhi acha nahi lagta.",
    "Tere jaane ke baad har din ek saza hai.",
    "Teri muskurahat se roshan ho jaati hai zindagi.",
    "Woh teri baat ab bhi dil ko choo jaati hai.",
    "Tu milta toh har gham door ho jaata.",
    "Tere saath bitaye pal sabse haseen the.",
    "Tu door sahi, lekin har khayal mein paas hai.",
    "Woh teri khamoshi bhi sab kuch keh jaati thi.",
    "Tujhse mohabbat ek silsila tha, jo kabhi khatam nahi hua.",
    "Tere hone ka asar har jagah dikhta hai.",
    "Tu chala gaya lekin yaadein reh gayi.",
    "Tere bina har pal adhoora lagta hai."
  ];
  
  function getRandomShayari() {
    const randomIndex = Math.floor(Math.random() * shayariList.length);
    return shayariList[randomIndex];
  }
  
  function showNewShayari() {
    const displayDiv = document.querySelector(".apt");
    if (displayDiv) {
      displayDiv.textContent = getRandomShayari();
    }
  }
  
  // Link the button after DOM is ready
  document.addEventListener("DOMContentLoaded", () => {
    const btn = document.querySelector(".clck");
    if (btn) {
      btn.addEventListener("click", showNewShayari);
    }
  });
  